apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "juice-shop.fullname" .) .Values.service.name }}
  labels:
    {{- include "juice-shop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: juice-shop
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
