apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "juice-shop.fullname" .) .Values.service.name }}
  labels:
    {{- include "juice-shop.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key ($value | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: juice-shop
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
